name: gitleaks
on:
  pull_request:
  push:
  workflow_dispatch:
jobs:
  scan:
    name: Run Gitleaks Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Create gitleaks.toml file
        run: |
          cat <<EOF > /tmp/gitleaks.toml
title = "Gitleaks Configuration"

# Custom rule to catch specific AWS secrets
[[rules]]
description = "Custom rule to catch AWS secrets"
regex = '''AKIA[0-9A-Z]{16}'''
tags = ["aws", "key"]

# Use the built-in rules as well
# No need to redefine these; they will be used automatically unless explicitly disabled

[allowlist]
paths = [
  ".github/workflows/gitleaks.yml",
  "another_ignored_path/*",
  "config/whitelisted_file.yaml"
]

commits = [
  "abcd1234efgh5678ijkl9012mnopqrstuvwx"
]

rule_ids = [
  "some-rule-id",
  "some-other-rule-id"
]

secret = [
  "AKIAIOSDNKOW7EXAMPLE",
  "another_allowed_secret"
]

# Example rules for others to add more custom configurations
[[rules]]
description = "Example rule to ignore specific secrets"
regex = '''dummy_secret=\w{32}'''
tags = ["example"]

[[rules]]
description = "Another example rule"
regex = '''some_other_secret=\w{16}'''
tags = ["example", "other"]

          EOF

      - name: verify gitleaks.toml 
        run: cat /tmp/gitleaks.toml

      - name: Run Gitleaks with generated config
        uses: gitleaks/gitleaks-action@v2
        env:
          GITLEAKS_CONFIG: /tmp/gitleaks.toml
