name: gitleaks
on:
  pull_request:
  push:
  workflow_dispatch:
jobs:
  create-toml:
    name: Create Gitleaks Config
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code1
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Create gitleaks.toml file
        run: |
          cat <<EOF > $GITHUB_WORKSPACE/gitleaks.toml
          title = "Gitleaks Configuration"

          [[rules]]
          description = "Rule to ignore specific secrets"
          regex = '''dummy_secret=\w{32}'''
          tags = ["example"]

          [allowlist]
          paths = [
            ".github/workflows/gitleaks.yml",
            "another_ignored_path/*",
            "config/whitelisted_file.yaml"
          ]
          commits = [
            "abcd1234efgh5678ijkl9012mnopqrstuvwx",
            "1234abcd5678efgh9012ijklmnopqrstuvwx"
          ]
          rule_ids = [
            "some-rule-id",
            "some-other-rule-id"
          ]
          secret = [
            "AKIAIOSDNKOW7EXAMPLE",
            "AKIAIOSDNKOW73XXMPL3",
            "another_allowed_secret"
          ]
          EOF

      - name: Verify gitleaks.toml file1
        run: cat $GITHUB_WORKSPACE/gitleaks.toml
        
  scan:
    name: Run Gitleaks Scan
    runs-on: ubuntu-latest
    needs: create-toml
    steps:
      - name: Checkout Code2
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Verify gitleaks.toml file2
        run: cat $GITHUB_WORKSPACE/gitleaks.toml

      - name: Run Gitleaks with generated config
        uses: gitleaks/gitleaks-action@v2
        env:
          CONFIG_PATH: $GITHUB_WORKSPACE/gitleaks.toml
        with:
          working-directory: $GITHUB_WORKSPACE

  
